[package]
name = "stremio-example-seed"
version = "0.1.0"
authors = ["Ivo Georgiev <ivo@stremio.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]


[dev-dependencies]
wasm-bindgen-test = "0.2.50" # NOTE: keep in sync with `wasm-bindgen` version

[dependencies]
serde = { version = "^1.0.102", features = ["derive"] }
wasm-bindgen = { version = "0.2.50", features = ["serde-serialize"]  }
futures = "0.1"
serde_json = "1.0.41"
wasm-bindgen-futures = "0.3"
js-sys = "0.3"
enclose = "1.1.8"

seed = "0.4.2"
#seed = { git = "ssh://git@github.com/David-OConnor/Seed.git" }

#stremio-core = { git = "ssh://git@github.com/Stremio/stremio-core.git" }
stremio-core = { path = "../stremio-core" }

#stremio-derive = { git = "ssh://git@github.com/Stremio/stremio-core.git" }
stremio-derive = { path = "../stremio-core/stremio-derive" }

#env-web = { git = "ssh://git@github.com/Stremio/stremio-core.git" }
env-web = { path = "../stremio-core/env-web" }

[dependencies.web-sys]
version = "0.3.30"
features = [
	'Window',
	'Request',
	'RequestInit',
	'Response',
	'Storage'
]


[profile.release]
lto = true
opt-level = 's'

