[package]
name = "stremio-example-seed"
version = "0.1.0"
authors = ["Ivo Georgiev <ivo@stremio.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]

[dependencies]
seed = "^0.3.4"
serde = { version = "^1.0.85", features = ["derive"] }
wasm-bindgen = { version = "0.2.40", features = ["serde-serialize", "nightly"]  }
console_error_panic_hook = { version = "0.1.1", optional = true }
wee_alloc = { version = "0.4.3", optional = true }
stremio-core = { git = "ssh://git@github.com/Stremio/stremio-core.git" }
stremio-derive = { git = "ssh://git@github.com/Stremio/stremio-core.git", package = "stremio-derive" }
futures = "0.1"
serde_json = "1.0.16"
wasm-bindgen-futures = "0.3"
js-sys = "0.3"
enclose = "0.1.3"

[profile.release]
lto = true
opt-level = 's'

[dependencies.web-sys]
version = "0.3.19"
features = [
	'Window',
	'Request',
	'RequestInit',
	'Response',
	'Storage'
]

